### ISSUE TITLE
Feature idea: Init Git repo

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cli#69]
Similar to the Laravel installer, initialise a Git repo when everything is done.

If I knew the best place to add this, I'd happily contribute.

**Comment by robdekort** [comment]
Yeah that would be great. I currently do it in the [Peak installer](https://github.com/studio1902/statamic-peak/blob/504cad5b6d3b020e8d083f6dcf78e93c73862033/StarterKitPostInstall.php#L91). Perhaps that helps. 

I also offer the following options in there if you choose to create a git repo:

- Exclude build folder from git.
- Exclude forms folder from git.
- Exclude users folder from git.
- Create a private or public repo on github.com when the GH CLI is installed (this is really useful imo).

I would be happy if this stuff would move to the Statamic CLI because it would benefit everyone installing Statamic. Feel free to use it.
